#! /bin/bash

temp=$1

grep -E '<td>'.*'<\/td>' $temp | sed '/<td><\/td>/d' | sed 's/<td>\(.*\)<\/td>/\1/g' | sed -n 2~2p | sed 's/<u>\(.\)<\/u>/\1/g' | tr , '\n' | sed 's/^[ \t]*//' | tr ' ' '\n' | sed '/^$/d' | sed "s/\`/'/g" | tr A-Z a-z | sed "/[^pk'mnwlhaeiou]/d" | sort -u
